language: java

sudo: false   # Linux OS: run in container

addons:
  apt:
    packages:
      - oracle-java8-installer

install: true

before_script:
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

script:
  - gradle assemble
  - gradle check # for better debug output, use "--debug --stacktrace" flags on this line
